### ISSUE TITLE
Incorrect paths in sim_local and sim_local_cw4.launch

### ISSUE THREAD

**Issue by valschmidt** [CCOMJHC/project11#18]
Launching sim_local.launch and sim_local_cw4.launch fail because they refer to `ben_project/parameters/ben.yaml` which doesn't exist in this location. The parameters directory doesn't exist and the yaml files now live in `config/`.

**Comment by rolker** [comment]
The whole launch directory needs to be cleaned out. As the project11 package was growing out of hand, things got split up into smaller, easier to manage packages. The project11_simulation package has the current launch files I use for simulation.

**Comment by rolker** [comment]
#20 removes these deprecated files.
